language: java
dist: trusty
jdk:
- oraclejdk8
install: true
script:
- gradle -b ice-adapter/build.gradle shadowJar -Pversion=${TRAVIS_TAG}
- mv ./ice-adapter/build/libs/ice-adapter-*-all.jar ./faf-ice-adapter.jar
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: faf-ice-adapter.jar
  skip_cleanup: true
  on:
    repo: FAForever/java-ice-adapter
    tags: true
  prerelease: true
all_branches: true
